name = "TextGraphs"
uuid = "1da7d4ca-ffb9-4e95-b99a-7e8e4561fc9a"
authors = ["fargolo <felipe.c.argolo@protonmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
